### ISSUE TITLE
Counter not initialized with unsupported extension in tolerant mode 

### ISSUE THREAD

**Issue by DomDerrien** [rhiokim/grunt-sloc#13]
If I have a filter for '**.styl' files, your code fails because the counter for the fallback extension `js` has not been initialized.

You need to move the [code initializing the counter](https://github.com/rhiokim/grunt-sloc/blob/master/tasks/sloc.js#L53-55) one block down (to have it after the `ext = 'js'` piece of code).

Thanks, Dom

**Comment by rhiokim** [comment]
It was fixed with latest commit.
