### ISSUE TITLE
Cannot benefit from grunt negate matches

### ISSUE THREAD

**Issue by DomDerrien** [rhiokim/grunt-sloc#14]
I would like to be able to exclude files from the directories to be parsed. For example, I would like to specify:
```
css: {
   'src/client': [ '**/**.styl', '!**/libs/**' ]
}
```

You could support them with the following lines added before the [call to `sloc(source, ext)`](https://github.com/rhiokim/grunt-sloc/blob/master/tasks/sloc.js#L67):
```
if (grunt.file.match(srcFilters, [f]).length === 0) {
   return;
}
```

Thanks, Dom

**Comment by arnabk** [comment]
+1

**Comment by rhiokim** [comment]
Now It could be able to available. Thanks for waiting.

**Comment by brownknows** [comment]
It would be really nice to add this to the documentation.   I spent an entire day wrestling with this until I found the commit referenced above.
