### ISSUE TITLE
Support LESS

### ISSUE THREAD

**Issue by erikdonohoo** [rhiokim/grunt-sloc#18]
I was looking through the code.  I see it supports SASS.  Is there any change besides adding an entry for `less` in the array to support LESS?  If this is the case, can I submit a PR for it?

**Comment by epikhighs** [comment]
@erikdonohoo 
Where's that array for file types?  I was going through the sloc.js code and don't see it...

https://github.com/rhiokim/grunt-sloc/blob/master/tasks/sloc.js

**Comment by erikdonohoo** [comment]
My bad.  I was looking at the actual sloc repo, not grunt-sloc.  But there current PR #17 should fix this anyway

**Comment by rhiokim** [comment]
It was so... lately fixed. Thanks for waiting
Now it was supported.
