### ISSUE TITLE
Does not appear to be working

### ISSUE THREAD

**Issue by sanfords** [rhiokim/grunt-sloc#9]
```
app
|-- Gruntfile.js
|-- notes.txt
```

sloc@0.0.4
grunt-sloc 0.4.2
grunt-cli v0.1.11
grunt v0.4.2
Mac OS X 10.9.1

```
'sloc': {
	'files': {
		'./' : ['*.txt'],
	}
},
```

Upon `cd app; grunt 'sloc'`, I only get:

```
Running "sloc:files" (sloc) task

Done, without errors.
```

Am I missing something?

**Comment by rhiokim** [comment]
https://github.com/flosse/sloc#supported-languages
